# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: nodejs10

# Defaults to "serve index.php" 
# entrypoint: serve helloworld.php

handlers:
#- url: /static
#  static_dir: static
# If your main page is index.php, comment the above entrypoint setting 

- url: .*
  script: auto

env_variables:
  GCLOUD_STORAGE_BUCKET: cs4750db-csvexport